server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/udemy-db?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 

eureka:
  instance:
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone:  http://eureka-server:8766/eureka
    fetch-registry: true
    register-with-eureka: true
